### ISSUE TITLE
Error - bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by Diullei** [xperiments/TSDoc#3]
I installed the `tsdoc` using:

```
npm install -g tsdoc
```

when I try execute:

```
tsdoc -i
```

I have the following message:

```
bash: /usr/bin/tsdoc: /usr/local/bin/node: bad interpreter: No such file or directory
```

What am I doing wrong?

**Comment by xperiments** [comment]
What os are you running it?

We have dev for osx , also we know there are some problems in win that we
are investigating

**Comment by xperiments** [comment]
Also if you are on OSX or linux, can you test the development branch?

**Comment by xperiments** [comment]
Diullei can you test if upgrading to v0.0.4 fix the error?

**Comment by Diullei** [comment]
Hi, I'm using ubuntu. But I have this problem with windows too. I'll test the development branch and the new version (v0.0.4).

**Comment by Diullei** [comment]
Now, it's working to me. Thanks!
